---
title:               Computer Stuff
tagline:             Clever tagline.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Mike Starr
twitter:             go2starr
github:              go2starr
email:               go2starr@gmail.com
google_analytics_id: YOUR_GA_ID
